version: '3'
services:
  front:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=local
    volumes:
    - ./:/usr/src/app:cached
#    command: sh -c "cd front && yarn start"
    ports:
    - "3100:3100"